version: "2"
services:
  homebridge:
    build: .
    hostname: homebridge
    container_name: homebridge
    command: "homebridge"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/homebridge:/root/.homebridge
      - /var/run/dbus:/var/run/dbus
    restart: always
